[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[project]
name = "knotted_graph"
version = "0.1.3"
description = "A computational package for spatial graphs and graph polynomial invariants."
authors = [
    {name = "Xianquan (Sarinstein) Yan", email = "xianquanyan@gmail.com"},
    {name = "Hakan Akgün", email = "hakanakgun317@gmail.com"},
]
maintainers  = [
    {name = "Xianquan (Sarinstein) Yan", email = "xianquanyan@gmail.com"},
    {name = "Hakan Akgün", email = "hakanakgun317@gmail.com"},
]
keywords = [
    "spatial graph",
    "Yamada polynomial",
    "graph invariants",
    "non-Hermitian topology",
    "nodal structure",
    "exceptional surface",
    "knotted graph",
    "spatial multigraph",
    "skeleton graph",
    "morphological image processing",
    "medial axis",
]
readme = {"file" = "README.md", "content-type" = "text/markdown"}
license = {file = "LICENSE"}
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "numpy",
    "sympy",
    "networkx",
    "matplotlib",
    "joblib",
    "shapely",
    "fastrdp",
    "tqdm",
]

[project.optional-dependencies]
nodal = [
    "poly2graph",
    "scikit-image",
    "pyvista[all]",
    "minorminer",
    "tabulate",
]
surface = [
    "pyvista[all]",
]
viz = [
    "plotly",
    "kaleido",
    "pdf2image",
    "pillow",
    "pymupdf",
]
repulsion = [
    "biopython",
    "plotly",
    "kaleido",
]
notebook = [
    "jupyterlab",
]
all = [
    "biopython",
    "igraph",
    "jupyterlab",
    "kaleido",
    "minorminer",
    "plotly",
    "poly2graph",
    "pyvista[all]",
    "scikit-image",
    "tabulate",
    "pdf2image",
    "pillow",
    "pymupdf",
]

[project.scripts]
kg-repulsive-layout = "knotted_graph.repulsive_layout.cli:main"

[project.urls]
Homepage = "https://github.com/sarinstein-yan/KnottedGraph"
Repository = "https://github.com/sarinstein-yan/KnottedGraph"
PyPI = "https://pypi.org/project/knotted_graph/"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]
