[build-system]
requires = ["uv_build>=0.9.18,<0.13.0"]
build-backend = "uv_build"

[project]
name = "knotted_graph"
version = "0.2.0"
description = "A computational package for spatial graphs and graph polynomial invariants."
authors = [
    {name = "Xianquan (Sarinstein) Yan", email = "xianquanyan@gmail.com"},
    {name = "Hakan Akgün", email = "hakanakgun317@gmail.com"},
]
maintainers  = [
    {name = "Xianquan (Sarinstein) Yan", email = "xianquanyan@gmail.com"},
    {name = "Hakan Akgün", email = "hakanakgun317@gmail.com"},
]
keywords = [
    "spatial graph",
    "spatial multigraph",
    "skeleton graph",
    "knotted graph",
    "Yamada polynomial",
    "graph invariants",
    "morphological image processing",
    "skeletonization",
    "handlebody",
    "compression body",
]
readme = {"file" = "README.md", "content-type" = "text/markdown"}
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "numpy",
    "sympy",
    "networkx",
    "matplotlib",
    "joblib",
    "shapely",
    "fastrdp",
    "tqdm",
]

[project.optional-dependencies]
nodal = [
    "poly2graph",
    "scikit-image",
    "pyvista[all]",
    "minorminer",
    "tabulate",
]
surface = [
    "pyvista[all]",
]
viz = [
    "plotly",
    "kaleido",
    "pdf2image",
    "pillow",
    "pymupdf",
]
repulsion = [
    "biopython",
    "plotly",
    "kaleido",
]
notebook = [
    "jupyterlab",
]
all = [
    "biopython",
    "igraph",
    "jupyterlab",
    "kaleido",
    "minorminer",
    "plotly",
    "poly2graph",
    "pyvista[all]",
    "scikit-image",
    "tabulate",
    "pdf2image",
    "pillow",
    "pymupdf",
]

[project.scripts]
kg-repulsive-layout = "knotted_graph.layout.repulsive.cli:main"

[project.urls]
Homepage = "https://github.com/sarinstein-yan/KnottedGraph"
Repository = "https://github.com/sarinstein-yan/KnottedGraph"
Documentation = "https://sarinstein-yan.github.io/KnottedGraph/"
Issues = "https://github.com/sarinstein-yan/KnottedGraph/issues"
PyPI = "https://pypi.org/project/knotted_graph/"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]
docs = [
    "jupytext",
    "myst-nb",
    "myst-parser",
    "nbclient",
    "pydata-sphinx-theme",
    "sphinx>=7,<9",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-design",
]

[tool.ruff.lint.per-file-ignores]
"src/knotted_graph/__init__.py" = ["F403"]
"src/knotted_graph/core/__init__.py" = ["F403"]
"src/knotted_graph/invariants/yamada/__init__.py" = ["F403"]
"src/knotted_graph/applications/nodal/__init__.py" = ["F403"]
"src/knotted_graph/visualization/__init__.py" = ["F403"]
"src/knotted_graph/applications/materials.py" = ["F822"]
